### ISSUE TITLE
yaml file sequence items

### ISSUE THREAD

**Issue by lukeab** [mozilla/sops#514]
Ubuntu 18.04 and archlinux
sops v3.3.1

Have weird yaml thing, encrypted a file with lines that looks like

```yaml
  ENV:
  - name: "AWS_KEY"
    value: "BLAHBLAHBLAH"
  - name: "AWS_REGION"
    value: "eu-west-1"
... etc..
```

SO i do `sops --encrypt file.yaml --output > file-sops.yaml
then do sops --decrypt file-sops.yaml > file-dec.yaml
the decrypted file now has those lines looking like

```yaml
    ENV:
    -   name: AWS_KEY
        value: BLAHBLAHBLAH
    -   name: AWS_REGION
        value: eu-west-1
```

So, it's changed the yaml indent to 4 spaces, that's fine, it's in the spec,
But it's added 2 spaces to the 1 space that was between the key and the `-` for each sequence item key 
yamlint blows up on this. though it doesn't cause issues in the python script that i then pass this config yaml to in my usecase, the CI issues yamllint causes are the problem.

The resulting yamllint output on my actual file, shows up like:
```
yamllint activity-dec.yaml 
activity-dec.yaml
  1:1       warning  missing document start "---"  (document-start)
  10:8      error    too many spaces after hyphen  (hyphens)
  10:5      error    wrong indentation: expected 8 but found 4  (indentation)
  12:8      error    too many spaces after hyphen  (hyphens)
  14:8      error    too many spaces after hyphen  (hyphens)
  16:8      error    too many spaces after hyphen  (hyphens)
...etc...

```

**Comment by lukeab** [comment]
reproduced the issue with a standalone file

### myfile.yaml
```yaml
ENV:
- name: AWS_KEY
  value: BLAHBLAHBLAH
- name: AWS_REGION
  value: eu-west-1

```
`SOPS_PGP_FP=<<mykey>> sops --encrypt myfile.yaml --output > myfile.sops.yaml`
`SOPS_PGP_FP=<<mykey>> sops --decryptt myfile.sops.yaml --output > myfile.dec.yaml`
```bash
~$> cat myfile.dec.yaml
ENV:
-   name: AWS_KEY
    value: BLAHBLAHBLAH
-   name: AWS_REGION
    value: eu-west-1
~$> yamllint myfile.dec.yaml
myfile.dec.yaml
  1:1       warning  missing document start "---"  (document-start)
  2:4       error    too many spaces after hyphen  (hyphens)
  2:1       error    wrong indentation: expected 2 but found 0  (indentation)
  4:4       error    too many spaces after hyphen  (hyphens)

```

**Comment by lukeab** [comment]
just a note, origional bug was encountered while use aws kms for encryption, so doesn't seem to be related to encryption type anywya.

**Comment by autrilla** [comment]
It seems to me that the output is spec compliant. We don’t really make any
guarantees on the styling of the YAML, and we especially do not guarantee
the output style will be consistent with the input style. The yaml library
we use has now been updated such that we could theoretically support it,
but nobody has put in the time yet.

**Comment by lukeab** [comment]
hmm, seems there is a yamllint flag to control the number of spaces allowed after a hyphen
https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.hyphens

I assumed since, by default, yamllint threw an error, it was actually a violation of the spec, not just a style concern, but now you have cast doubt on my assumption. Is there any rules in the spec about spaces after sequence item hyphens? 

I thought i might try fix it, but you say there is a new library in use, i'd give it a shot, but i haven't been able to find where in the code this fix could be affected easily yet. A pointer in the right direction would be motivating for me to try again.

**Comment by lukeab** [comment]
Answering my own uncertainty: had a look at the spec
https://yaml.org/spec/1.2/spec.html#id2759963
and
https://yaml.org/spec/1.2/spec.html#id2797382

Seems it just says 

> The “-” indicator must be separated from the node by white space. 

So there's no guarantee in the spec that it should be only one space character.

**Comment by kunickiaj** [comment]
Ran into this as well, formatting inconsistency from the rest of our files is a bit inconvenient. Would also be interesting in understanding where we could add support for control of the formatting.

**Comment by autrilla** [comment]
@kunickiaj we would need to upgrade to https://github.com/go-yaml/yaml/tree/v3, parsing into https://godoc.org/gopkg.in/yaml.v3#Node.

FWIW, SOPS does not reorder keys. https://github.com/mozilla/sops/issues/300#issuecomment-367942757 has more information on why the comment behavior you see happens.

**Comment by vitali-shcharbin** [comment]
In some cases, it also replaces 2 spaces with 4, for example:
```
key.key.key:
  key1: value1
  key2: value2
  ...
```
becomes:
```
key.key.key:
    key1: value1
    key2: value2
    ...
```

**Comment by rbabyuk** [comment]
hi all,

I am hitting this issue as well,
sops version is 3.6.1

**Comment by onedr0p** [comment]
I ran into this issue too...

```yaml
key: ENC[AES256_GCM,data:WT/gj1y+bKWNHSYeklKIrphPZ2RTOM8NzlG09Z0HXFzbiYkVp7YVFzg=,iv:mPcv1If6SwfBZW+6FwMlrBmM+xssKvM8jIYHuNEn1B0=,tag:da9P55ZRxDt9lBVv/LkemA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-03T20:45:32Z'
    mac: ENC[AES256_GCM,data:sqFu3XksD/IKE4b6WFW/hJ39ba//PD4YikgmENv2K4rNcR0nZCh5e/sEUPKSDIkUM+fyZeNlwwxodhh5oVMsY+0bQ5ISWbH+dxi+h3j1GrMgfms+EYImik49bjSYbcYBj9BeUWtnzz8Ab/PHUqMrbIMNVaHWAfbuClbooYmyKeQ=,iv:tbDF2y3+86qrKEDv8vJS2zIBB/PzJUe20nLX513+5s8=,tag:3GeY6ZqqSdFJqvzVMzcmhA==,type:str]
    pgp:
    -   created_at: '2021-01-27T18:14:44Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAyUpShfNkFB/AQf/RxF3NLkoonJP4wQqELkfPtJl5Oar1UH7OBYwzep3uEPE
            MCPFeI/Fdr/8WxT0x6ieUC7odZX1J9tNzUeStyaWCS3CX6+zmEb0uavV7RlewdFc
            noIPyM7Q4R6/L6QyGWx6aPwkUq8qvH+8hk6VdqtAdipY8uBVogO/+BHd502nE+5E
            WqzxRFxFr7/6mjFHrPYcab5QvSoVc3Lrhh08hKXJYpquPrjDI4VYkJhTxmbaZK5w
            e676rq+eob8tQ7Nz2nnw5W51Oy/i2Yt6Q/wHj5dSPc4g+LMVUPwdx72+OB829uZR
            3FNKH2EJ6BCVVOe7JUueeoHjz1/UCooAx9vwAlJ8MNJeAbrEJPL1OUEJfkqJuoQk
            v4LGyJD4Gi+58FqLcOpx1DGqNsMZ8ElGKbBUKC3Resksd4K4uTfMyy0HwDRpvUdG
            M47W5K9K28MePouf7T/lsemwoYB59GSoeqIviyeteQ==
            =DSca
            -----END PGP MESSAGE-----
        fp: 3D16CEE4A27381B4
    unencrypted_suffix: _unencrypted
    version: 3.6.1
```

and yamllint output:

```
yamllint secret.enc.yaml
my-secrets.enc.yaml
  1:1       warning  missing document start "---"  (document-start)
  10:8      error    too many spaces after hyphen  (hyphens)
  10:5      error    wrong indentation: expected 8 but found 4  (indentation)
```

The only workaround I found is to have `yamllint` ignore filenames matching a certain regex, which works until you need to embed the `sops` data into an existing yaml file.

**Comment by felixfontein** [comment]
This should be fixed by the change to yaml.v3 in the current `develop` branch.

**Comment by onedr0p** [comment]
I can confirm formatting is still the same, even with the new release.

**Comment by felixfontein** [comment]
The latest version uses a different YAML library, and lists are definitely serialized differently. So formatting is definitely *not* the same. If yamllint likes the new style better is another question :-)

**Comment by onedr0p** [comment]
You are correct @felixfontein apologies, I did not test the right binary :(

Before...

```yaml
    pgp:
    -   created_at: '2021-01-27T18:14:44Z'
        enc: |
```

After...

```yaml
    pgp:
        - created_at: "2021-03-25T00:36:44Z"
          enc: |
```

**Comment by almereyda** [comment]
> Would also be interesting in understanding where we could add support for control of the formatting.

It appears support for https://editorconfig.org/ would also allow us to make some linters happy.

**Comment by Ph0tonic** [comment]
Hi,
I think that this issue can be closed as the formatting is now different and the indentation can now be configured.
