### ISSUE TITLE
Master branch CI

### ISSUE THREAD

**Issue by tswanson-cs** [mozilla/sops#800]
I tried to fork the repo and run the tests.  There appears to be issues with the master branch.

        stores/ini/store.go:292: conversion from int64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
        FAIL	go.mozilla.org/sops/v3/stores/ini [build failed]

Is there a reason the master branch build is breaking your CI?

<img width="849" alt="Screen Shot 2021-01-17 at 11 25 19 PM" src="https://user-images.githubusercontent.com/9701912/104884477-4580f380-591b-11eb-94ca-018d413928fe.png">

Please let me know what I can do to help get this fixed and the master back to a clean state.  😄

**Comment by tswanson-cs** [comment]
> I tried to fork the repo and run the tests. There appears to be issues with the master branch.

Fixed with this pull request:
 Remove dead broken code #793

**Comment by tswanson-cs** [comment]
Seems the use with gpg2 is not stable, I see many issues on git with work arounds.  It would be of use to create another version of keysource.go that is more stable with gpg2.  A legacy mode would be kept but have an option to specify 1 or 2 for gpg version.  For now I have downgraded my gpg to gpg1....

**Comment by speculatrix** [comment]
this is still a problem, I git cloned a fresh copy and couldn't build from the master branch.

**Comment by speculatrix** [comment]
and I tried to build from the "develop" branch but that's currently broken :-(

**Comment by autrilla** [comment]
Yeah, we need https://github.com/mozilla/sops/pull/832 to be merged to fix it. https://github.com/mozilla/sops/commit/e2d6d0fdc30b7626f4a660dd7f21b2db583fae57 should be good to build from.

**Comment by autrilla** [comment]
FWIW, this is a good reason to use https://github.com/bors-ng/bors-ng, because that tests pass before merge doesn't mean that they will after.
